name: msal_flutter
description: A Microsoft Authentication Library wrapper for Android and iOS
version: 1.0.0+2
homepage: https://github.com/moodio/msal-flutter
repository: https://github.com/moodio/msal-flutter
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: uk.co.moodio.msal_flutter
    pluginClass: MsalFlutterPlugin